# Generated by Django 3.0.2 on 2020-01-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=250)),
                ('attachment', models.FileField(upload_to='')),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='map.Profile')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='map.Profile')),
            ],
        ),
    ]
