# Generated by Django 3.0.2 on 2020-01-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follow', to='map.Profile'),
        ),
    ]
