# Generated by Django 3.0.1 on 2020-01-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200129_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(),
        ),
    ]
